apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: todo-notification:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: todoapp-config
              key: NODE_ENV
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: todoapp-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: todoapp-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: todoapp-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todoapp-secrets
              key: RABBITMQ_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
