apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secrets
  namespace: todoapp
type: Opaque
data:
  POSTGRES_USER: dG9kb3VzZXI=
  POSTGRES_PASSWORD: dG9kb3Bhc3MxMjM=
  POSTGRES_DB: dG9kb2FwcA==
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==
  RABBITMQ_USER: YWRtaW4=
  RABBITMQ_PASSWORD: YWRtaW5wYXNzMTIz